export { ReactComponent as PlusIcon } from '@/components/Icon/svg/PlusIcon.svg'
export { ReactComponent as ArrowRightIcon } from '@/components/Icon/svg/ArrowRightIcon.svg'
export { ReactComponent as ImgFallbackIcon } from '@/components/Icon/svg/ImgFallbackIcon.svg'
export { ReactComponent as SearchIcon } from '@/components/Icon/svg/SearchIcon.svg'
export { ReactComponent as LoadingIcon } from '@/components/Icon/svg/LoadingIcon.svg'
export { ReactComponent as CheckCircleFillIcon } from '@/components/Icon/svg/CheckCircleFillIcon.svg'
export { ReactComponent as XCircleFillIcon } from '@/components/Icon/svg/XCircleFillIcon.svg'
export { ReactComponent as XIcon } from '@/components/Icon/svg/XIcon.svg'
export { ReactComponent as CheckIcon } from '@/components/Icon/svg/CheckIcon.svg'
export { ReactComponent as CopyIcon } from '@/components/Icon/svg/CopyIcon.svg'

export { default as LogoIcon } from '@/components/Icon/svg/LogoIcon'
export { default as GithubIcon } from '@/components/Icon/svg/GithubIcon'
